### ISSUE TITLE
[USER STORY]As a normal user, I want to login or register to my account so that I can view my account details.

### ISSUE THREAD

**Issue by JIAYI615** [JIAYI615/SOEN341-team-project#10]
**TASK:
- [x] #11 
- [x] #13 
- [x] #12

**Comment by pavithrasiv** [comment]
The user can now login or register to their account.

**Comment by JIAYI615** [comment]
Task finished with applying pair programming!

**Comment by BrainOverfl0w** [comment]
User story complete! Closing the issue now.
