### ISSUE TITLE
[USER STORY] As an admin, I want to add products so that other users can view them on the browsing page. 

### ISSUE THREAD

**Issue by BrainOverfl0w** [JIAYI615/SOEN341-team-project#2]
Tasks divided:
- [x] #14 
- [x] #15

**Comment by JIAYI615** [comment]
Applying the pair programming, combining everyone's effort to finish the implementation, and having communication when coding.

**Comment by BrainOverfl0w** [comment]
We have faced some issues, but using the pair programming technique we have resolved them successfully. Good job everyone !

**Comment by pavithrasiv** [comment]
The admin can now add products and thanks to pair programming, this user story was able to be implemented and issues were solved!

**Comment by JIAYI615** [comment]
The user story is finished! close this issue.
