### ISSUE TITLE
[USER STORY] As a normal user, I want to be able to comment the products I have ordered

### ISSUE THREAD

**Issue by JIAYI615** [JIAYI615/SOEN341-team-project#60]
## Acceptance Test
- Users go to the homepage, click the login button, and be directed to the login page
- User input the username and the password, if successfully log in, the user will be directed to the homepage, if not the user will be directed to the login page again or to the signup page.
- User can access the personal portal by clicking on the Myaccount link placed at the right up corner of the page
- After accessing the personal portal, the user can click the "view orders" link
- After clicking the link, users will be directed to the orders page. Users can click the view details button after a specific order
- After going to the order detail page, click the comment button at the right of the item bought.
- The comment page shows up, click the submit button after typing the comments
- After the submission, the user will be directed to the order detail page.

## TASK
- [x] #62

**Comment by BrainOverfl0w** [comment]
Done ! Closing issue
