### ISSUE TITLE
[USER STORY] As a normal user, I want to be able to check the comments of a product in product detail page.

### ISSUE THREAD

**Issue by JIAYI615** [JIAYI615/SOEN341-team-project#61]
## Acceptance Test
- On the homepage, users click the products images to access the product details
- On the product detail page, users scroll down and find the comment block at the bottom of the detail page
- In the comment block, the comments are listed in a linear fashion from the top to bottom

## TASK
- [x] #63

**Comment by BrainOverfl0w** [comment]
Done ? :D
